package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_3"
                name = "Docker Registry"
                userName = "mikhailshubin26"
                password = "credentialsJSON:4bfc25fb-bea9-40b4-a140-7a61f1df5a1d"
            }
        }
    }
}
